export const projectList = [
  {
    id: 1,
    img: "../public/projects/project1.png",
    title: "Project Tile goes here",
    text: "This is sample project description random things are here in description This is sample project lorem ipsum generator for dummy content",
    tstack: "HTML , JavaScript, SASS, React",
    links: "/link",
    git: "/gitlink",
  },
  {
    id: 2,
    img: "../public/projects/project2.png",
    title: "Project Tile goes here",
    text: "This is sample project description random things are here in description This is sample project lorem ipsum generator for dummy content",
    tstack: "HTML , JavaScript, SASS, React",
    links: "/link",
    git: "/gitlink",
  },
  {
    id: 3,
    img: "../public/projects/project3.png",
    title: "Project Tile goes here",
    text: "This is sample project description random things are here in description This is sample project lorem ipsum generator for dummy content",
    tstack: "HTML , JavaScript, SASS, React",
    links: "/link",
    git: "/gitlink",
  },
  {
    id: 4,
    img: "../public/projects/project4.png",
    title: "Project Tile goes here",
    text: "This is sample project description random things are here in description This is sample project lorem ipsum generator for dummy content",
    tstack: "HTML , JavaScript, SASS, React",
    links: "/link",
    git: "/gitlink",
  },
  {
    id: 5,
    img: "../public/projects/project5.png",
    title: "Project Tile goes here",
    text: "This is sample project description random things are here in description This is sample project lorem ipsum generator for dummy content",
    tstack: "HTML , JavaScript, SASS, React",
    links: "/link",
    git: "/gitlink",
  },
  {
    id: 6,
    img: "../public/projects/project6.png",
    title: "Project Tile goes here",
    text: "This is sample project description random things are here in description This is sample project lorem ipsum generator for dummy content",
    tstack: "HTML , JavaScript, SASS, React",
    links: "/link",
    git: "/gitlink",
  },
];
